// Generated by scripts/sync-journal.mjs. Do not edit by hand.
export const journalData = {
  "title": "Project Journal",
  "reviewedOn": "2026-08-31",
  "focus": "Natural-world foundation and the map and spatial model prototype",
  "milestone": {
    "id": "PROTO-001",
    "name": "map and spatial model prototype",
    "evidence": [
      {
        "source": "HANDOFF-CURRENT",
        "field": "body.contains",
        "equals": "**Immediate milestone:** `PROTO-001` — map and spatial model prototype"
      },
      {
        "source": "PROTO-001",
        "field": "front.implementation",
        "equals": "partial"
      }
    ]
  },
  "fingerprint": "7a51af690b33c471cd6c0181235471002110f3c7d665bd9c93ea4c9589d2a4d0",
  "counts": {
    "systems": 21,
    "acceptedConcepts": 17,
    "explorationTopics": 8,
    "openDecisions": 19,
    "conceptLifecycle": {
      "accepted": 17,
      "recognized": 8
    },
    "systemLinks": 35
  },
  "currentStatements": {
    "overview": "17 concepts are accepted; 8 topics remain in active exploration; 19 architecture decisions remain open.",
    "worldGeneration": {
      "lead": "A conceptual foundation and Rust runtime evidence exist; this Journal does not yet claim a working world generator.",
      "plainLanguage": "The repository contains 17 accepted world-generation concepts and 8 active exploration topics. Accepted concepts describe causal boundaries and relationships; they do not choose algorithms, storage layouts, or numerical methods.",
      "runtime": "Rust runtime evidence is present: Cargo.toml, src/application/mod.rs, src/lib.rs, src/main.rs.",
      "knowledge": "17 causal concepts are accepted; 8 later natural-system topics remain in exploration.",
      "coverage": "World-generation coverage is partial. The natural world remains intentionally incomplete until authority records otherwise.",
      "implementation": "Rust runtime evidence exists, but this Journal does not claim that the world generator is complete.",
      "attention": "World generation and the map prototype are current. Exploration topics have no assigned implementation order."
    }
  },
  "runtimeEvidence": {
    "rustPresent": true,
    "paths": [
      "Cargo.toml",
      "src/application/mod.rs",
      "src/lib.rs",
      "src/main.rs"
    ]
  },
  "systems": [
    {
      "id": "state-of-consequence",
      "name": "State of Consequence",
      "purpose": "Define a Christian-founded living nation simulation on one persistent Earth-like planet and the experience it must ultimately provide.",
      "kind": "product",
      "parent": null,
      "knowledgeState": "accepted",
      "coverage": "partial",
      "implementationState": "not-started",
      "attention": "supporting",
      "authorities": [
        "VISION-001",
        "PRINCIPLES-001",
        "BRAND-001"
      ],
      "documents": [
        "VISION-001",
        "PRINCIPLES-001",
        "BRAND-001"
      ],
      "worldGenerationConcepts": [],
      "openDecisions": [],
      "relationships": []
    },
    {
      "id": "living-nation-simulation",
      "name": "Living nation simulation",
      "purpose": "Let the player govern an autonomous nation through policy, institutions, infrastructure goals, resources, relationships, and long-term strategy.",
      "kind": "product",
      "parent": "state-of-consequence",
      "knowledgeState": "accepted",
      "coverage": "partial",
      "implementationState": "not-started",
      "attention": "later",
      "authorities": [
        "VISION-001",
        "PRINCIPLES-001"
      ],
      "documents": [],
      "worldGenerationConcepts": [],
      "openDecisions": [
        "ARCH-OPEN-015"
      ],
      "relationships": [
        {
          "type": "depends-on",
          "target": "natural-world-foundation"
        }
      ]
    },
    {
      "id": "player-map-experience",
      "name": "Player map experience",
      "purpose": "Let players govern from the nation view while navigating one continuous planet from continental to city scale with knowledge-limited foreign information.",
      "kind": "product",
      "parent": "state-of-consequence",
      "knowledgeState": "accepted",
      "coverage": "partial",
      "implementationState": "not-started",
      "attention": "supporting",
      "authorities": [
        "VISION-001",
        "PRINCIPLES-001",
        "ARCH-001"
      ],
      "documents": [],
      "worldGenerationConcepts": [],
      "openDecisions": [
        "ARCH-OPEN-018"
      ],
      "relationships": [
        {
          "type": "uses",
          "target": "runtime-architecture"
        },
        {
          "type": "supports",
          "target": "living-nation-simulation"
        }
      ]
    },
    {
      "id": "persistent-multiplayer",
      "name": "Persistent multiplayer",
      "purpose": "Connect changing sovereign nations on one persistent planet without weakening the depth, autonomy, or physical grounding of each nation simulation.",
      "kind": "product",
      "parent": "state-of-consequence",
      "knowledgeState": "accepted",
      "coverage": "partial",
      "implementationState": "not-started",
      "attention": "later",
      "authorities": [
        "VISION-001",
        "ARCH-001"
      ],
      "documents": [],
      "worldGenerationConcepts": [],
      "openDecisions": [
        "ARCH-OPEN-017"
      ],
      "relationships": [
        {
          "type": "depends-on",
          "target": "living-nation-simulation"
        },
        {
          "type": "uses",
          "target": "runtime-architecture"
        }
      ]
    },
    {
      "id": "optional-web3-layer",
      "name": "Optional Web3 layer",
      "purpose": "Preserve a possible future economic or ownership layer without allowing it to dictate the core simulation.",
      "kind": "product",
      "parent": "state-of-consequence",
      "knowledgeState": "accepted",
      "coverage": "partial",
      "implementationState": "not-started",
      "attention": "later",
      "authorities": [
        "VISION-001",
        "BRAND-001"
      ],
      "documents": [],
      "worldGenerationConcepts": [],
      "openDecisions": [],
      "relationships": [
        {
          "type": "depends-on",
          "target": "living-nation-simulation"
        }
      ]
    },
    {
      "id": "natural-world-foundation",
      "name": "Natural-world foundation",
      "purpose": "Create the coherent pre-human physical world inherited by every later nation system.",
      "kind": "product",
      "parent": "state-of-consequence",
      "knowledgeState": "partially-accepted",
      "coverage": "partial",
      "implementationState": "exploration",
      "attention": "now",
      "authorities": [
        "ROADMAP-001"
      ],
      "documents": [
        "ROADMAP-001"
      ],
      "worldGenerationConcepts": [],
      "openDecisions": [],
      "relationships": []
    },
    {
      "id": "world-generation",
      "name": "World generation",
      "purpose": "Build a causal natural history whose accumulated result becomes the playable physical world.",
      "kind": "product",
      "parent": "natural-world-foundation",
      "knowledgeState": "partially-accepted",
      "coverage": "partial",
      "implementationState": "unresolved",
      "attention": "now",
      "authorities": [
        "WG-INDEX",
        "WG-AUTHORING"
      ],
      "documents": [
        "WG-INDEX",
        "WG-AUTHORING"
      ],
      "worldGenerationConcepts": [],
      "openDecisions": [],
      "relationships": []
    },
    {
      "id": "planetary-foundation",
      "name": "Earth-like planetary foundation",
      "purpose": "Supply common physical rules, one stable Earth-like oblate reference ellipsoid per world, and bounded planetary causes before geological history begins.",
      "kind": "product",
      "parent": "world-generation",
      "knowledgeState": "accepted",
      "coverage": "partial",
      "implementationState": "unresolved",
      "attention": "supporting",
      "authorities": [
        "WG-001",
        "WG-025",
        "ARCH-DEC-002",
        "ADR-0002"
      ],
      "documents": [
        "WG-001",
        "WG-025",
        "ARCH-DEC-002",
        "ADR-0002"
      ],
      "worldGenerationConcepts": [
        "WG-001",
        "WG-025"
      ],
      "openDecisions": [
        "ARCH-OPEN-009",
        "ARCH-OPEN-019"
      ],
      "relationships": []
    },
    {
      "id": "geological-history-and-material",
      "name": "Geological history and material",
      "purpose": "Represent inherited geological events, material composition, material state, and geometry-changing operations.",
      "kind": "product",
      "parent": "world-generation",
      "knowledgeState": "accepted",
      "coverage": "partial",
      "implementationState": "unresolved",
      "attention": "supporting",
      "authorities": [
        "WG-002",
        "WG-003",
        "WG-004",
        "WG-006"
      ],
      "documents": [
        "WG-002",
        "WG-003",
        "WG-004",
        "WG-006"
      ],
      "worldGenerationConcepts": [
        "WG-002",
        "WG-003",
        "WG-004",
        "WG-006"
      ],
      "openDecisions": [
        "ARCH-OPEN-005",
        "ARCH-OPEN-012",
        "ARCH-OPEN-013",
        "ARCH-OPEN-014"
      ],
      "relationships": [
        {
          "type": "depends-on",
          "target": "planetary-foundation"
        }
      ]
    },
    {
      "id": "canonical-geological-world",
      "name": "Canonical geological world",
      "purpose": "Preserve sparse three-dimensional present truth, contextual physical state, deterministic refinement, and computational locality.",
      "kind": "product",
      "parent": "world-generation",
      "knowledgeState": "accepted",
      "coverage": "partial",
      "implementationState": "unresolved",
      "attention": "supporting",
      "authorities": [
        "WG-005",
        "WG-007",
        "WG-008",
        "WG-009",
        "ARCH-001"
      ],
      "documents": [
        "WG-005",
        "WG-007",
        "WG-008",
        "WG-009"
      ],
      "worldGenerationConcepts": [
        "WG-005",
        "WG-007",
        "WG-008",
        "WG-009",
        "WG-010",
        "WG-015",
        "WG-016"
      ],
      "openDecisions": [
        "ARCH-OPEN-002",
        "ARCH-OPEN-003",
        "ARCH-OPEN-004",
        "ARCH-OPEN-007"
      ],
      "relationships": [
        {
          "type": "depends-on",
          "target": "geological-history-and-material"
        }
      ]
    },
    {
      "id": "tectonic-evolution",
      "name": "Tectonic evolution",
      "purpose": "Turn plate motion and interactions into persistent tectonic structures and geological provinces.",
      "kind": "product",
      "parent": "world-generation",
      "knowledgeState": "accepted",
      "coverage": "partial",
      "implementationState": "unresolved",
      "attention": "supporting",
      "authorities": [
        "WG-011",
        "WG-012"
      ],
      "documents": [
        "WG-011",
        "WG-012"
      ],
      "worldGenerationConcepts": [
        "WG-011",
        "WG-012"
      ],
      "openDecisions": [
        "ARCH-OPEN-010",
        "ARCH-OPEN-011"
      ],
      "relationships": [
        {
          "type": "depends-on",
          "target": "planetary-foundation"
        },
        {
          "type": "feeds",
          "target": "geological-history-and-material"
        }
      ]
    },
    {
      "id": "broad-solid-earth-geometry",
      "name": "Broad solid-Earth geometry",
      "purpose": "Derive broad physical geometry and semantic ground or seafloor queries from inherited geology, buoyancy, loads, and response.",
      "kind": "product",
      "parent": "world-generation",
      "knowledgeState": "accepted",
      "coverage": "partial",
      "implementationState": "unresolved",
      "attention": "supporting",
      "authorities": [
        "WG-013"
      ],
      "documents": [
        "WG-013"
      ],
      "worldGenerationConcepts": [
        "WG-013",
        "WG-014"
      ],
      "openDecisions": [
        "ARCH-OPEN-008"
      ],
      "relationships": [
        {
          "type": "depends-on",
          "target": "tectonic-evolution"
        },
        {
          "type": "depends-on",
          "target": "canonical-geological-world"
        }
      ]
    },
    {
      "id": "surface-natural-systems",
      "name": "Surface natural systems",
      "purpose": "Explore how surface processes, water, climate, soils, ecosystems, resources, hazards, and engineering properties emerge from inherited physical causes.",
      "kind": "product",
      "parent": "world-generation",
      "knowledgeState": "recognized",
      "coverage": "exploratory",
      "implementationState": "not-investigated",
      "attention": "unassigned",
      "authorities": [
        "WG-INDEX"
      ],
      "documents": [],
      "worldGenerationConcepts": [
        "WG-017",
        "WG-018",
        "WG-019",
        "WG-020",
        "WG-021",
        "WG-022",
        "WG-023",
        "WG-024"
      ],
      "openDecisions": [
        "ARCH-OPEN-006"
      ],
      "relationships": [
        {
          "type": "depends-on",
          "target": "broad-solid-earth-geometry"
        }
      ]
    },
    {
      "id": "map-and-spatial-model-prototype",
      "name": "Map and spatial model prototype",
      "purpose": "Gather observable evidence about encoding, querying, presenting, and navigating the accepted planet-fixed physical frame; provisional planetary-reference code exists only in an isolated uncommitted worktree and began before the design-readiness gate passed.",
      "kind": "product",
      "parent": "natural-world-foundation",
      "knowledgeState": "accepted",
      "coverage": "complete-at-scope",
      "implementationState": "partial",
      "attention": "now",
      "authorities": [
        "PROTO-001"
      ],
      "documents": [
        "PROTO-001"
      ],
      "worldGenerationConcepts": [],
      "openDecisions": [
        "ARCH-OPEN-001"
      ],
      "relationships": [
        {
          "type": "constrained-by",
          "target": "canonical-geological-world",
          "evidence": [
            "PROTO-001",
            "ARCH-001"
          ]
        },
        {
          "type": "uses",
          "target": "runtime-architecture"
        }
      ]
    },
    {
      "id": "runtime-architecture",
      "name": "Runtime architecture",
      "purpose": "Keep curved planetary and simulation truth authoritative, persistent, and separate from derived presentation, player knowledge, and future networking.",
      "kind": "product",
      "parent": "state-of-consequence",
      "knowledgeState": "accepted",
      "coverage": "partial",
      "implementationState": "partial",
      "attention": "supporting",
      "authorities": [
        "ARCH-001",
        "ARCH-DEC-001"
      ],
      "documents": [
        "ARCH-001",
        "ARCH-DEC-001"
      ],
      "worldGenerationConcepts": [],
      "openDecisions": [
        "ARCH-OPEN-016"
      ],
      "relationships": []
    },
    {
      "id": "documentation-governance",
      "name": "Documentation governance",
      "purpose": "Keep project truth findable, consistently named, uniquely owned, and correctly routed.",
      "kind": "support",
      "parent": null,
      "knowledgeState": "operational",
      "coverage": "complete-at-scope",
      "implementationState": "operational",
      "attention": "supporting",
      "authorities": [
        "DOCS-001",
        "DOCS-INDEX",
        "DOCS-GLOSSARY",
        "DOCS-CLEAR-LANGUAGE"
      ],
      "documents": [
        "DOCS-001",
        "DOCS-INDEX",
        "DOCS-GLOSSARY",
        "DOCS-CLEAR-LANGUAGE"
      ],
      "worldGenerationConcepts": [],
      "openDecisions": [],
      "relationships": []
    },
    {
      "id": "project-journal",
      "name": "Project Journal and System Map",
      "purpose": "Translate current repository authority into a readable project overview while keeping dated explanations as history.",
      "kind": "support",
      "parent": null,
      "knowledgeState": "operational",
      "coverage": "complete-at-scope",
      "implementationState": "operational",
      "attention": "supporting",
      "authorities": [
        "DOCS-001"
      ],
      "documents": [],
      "worldGenerationConcepts": [],
      "openDecisions": [],
      "relationships": [
        {
          "type": "uses",
          "target": "documentation-governance"
        }
      ]
    },
    {
      "id": "knowledge-delivery",
      "name": "Knowledge delivery",
      "purpose": "Turn incomplete direction into bounded, reviewed, resumable documentation outcomes.",
      "kind": "support",
      "parent": null,
      "knowledgeState": "operational",
      "coverage": "complete-at-scope",
      "implementationState": "operational",
      "attention": "supporting",
      "authorities": [
        "DOCS-WORKFLOW",
        "AGENT-OUTCOME-LEAD",
        "AGENT-DEVELOPER",
        "AGENT-REVIEWER"
      ],
      "documents": [
        "DOCS-WORKFLOW",
        "AGENT-OUTCOME-LEAD",
        "AGENT-DEVELOPER",
        "AGENT-REVIEWER",
        "HANDOFF-KNOWLEDGE-WORKFLOW"
      ],
      "worldGenerationConcepts": [],
      "openDecisions": [],
      "relationships": [
        {
          "type": "supports",
          "target": "documentation-governance"
        }
      ]
    },
    {
      "id": "project-operations",
      "name": "Project operations",
      "purpose": "Report the current milestone, observed repository state, blockers, and immediate actions.",
      "kind": "support",
      "parent": null,
      "knowledgeState": "operational",
      "coverage": "complete-at-scope",
      "implementationState": "operational",
      "attention": "supporting",
      "authorities": [
        "HANDOFF-CURRENT"
      ],
      "documents": [
        "HANDOFF-CURRENT"
      ],
      "worldGenerationConcepts": [],
      "openDecisions": [],
      "relationships": [
        {
          "type": "uses",
          "target": "documentation-governance"
        }
      ]
    },
    {
      "id": "decision-governance",
      "name": "Decision governance",
      "purpose": "Keep unresolved choices separate from accepted decisions and preserve durable resolution records.",
      "kind": "support",
      "parent": null,
      "knowledgeState": "operational",
      "coverage": "complete-at-scope",
      "implementationState": "operational",
      "attention": "supporting",
      "authorities": [
        "DECISION-INDEX",
        "ARCH-OPEN"
      ],
      "documents": [
        "DECISION-INDEX",
        "ARCH-OPEN"
      ],
      "worldGenerationConcepts": [],
      "openDecisions": [],
      "relationships": [
        {
          "type": "supports",
          "target": "knowledge-delivery"
        }
      ]
    },
    {
      "id": "git-publication",
      "name": "Git publication",
      "purpose": "Record and publish an already validated result through an explicitly authorized Git transaction.",
      "kind": "support",
      "parent": null,
      "knowledgeState": "operational",
      "coverage": "complete-at-scope",
      "implementationState": "operational",
      "attention": "supporting",
      "authorities": [
        "AGENT-GIT-PUBLISHER"
      ],
      "documents": [
        "AGENT-GIT-PUBLISHER"
      ],
      "worldGenerationConcepts": [],
      "openDecisions": [],
      "relationships": [
        {
          "type": "depends-on",
          "target": "knowledge-delivery"
        },
        {
          "type": "uses",
          "target": "documentation-governance"
        }
      ]
    }
  ],
  "systemLinks": [
    {
      "source": "living-nation-simulation",
      "sourceName": "Living nation simulation",
      "type": "part-of",
      "target": "state-of-consequence",
      "targetName": "State of Consequence"
    },
    {
      "source": "living-nation-simulation",
      "sourceName": "Living nation simulation",
      "type": "depends-on",
      "target": "natural-world-foundation",
      "targetName": "Natural-world foundation"
    },
    {
      "source": "player-map-experience",
      "sourceName": "Player map experience",
      "type": "part-of",
      "target": "state-of-consequence",
      "targetName": "State of Consequence"
    },
    {
      "source": "player-map-experience",
      "sourceName": "Player map experience",
      "type": "uses",
      "target": "runtime-architecture",
      "targetName": "Runtime architecture"
    },
    {
      "source": "player-map-experience",
      "sourceName": "Player map experience",
      "type": "supports",
      "target": "living-nation-simulation",
      "targetName": "Living nation simulation"
    },
    {
      "source": "persistent-multiplayer",
      "sourceName": "Persistent multiplayer",
      "type": "part-of",
      "target": "state-of-consequence",
      "targetName": "State of Consequence"
    },
    {
      "source": "persistent-multiplayer",
      "sourceName": "Persistent multiplayer",
      "type": "depends-on",
      "target": "living-nation-simulation",
      "targetName": "Living nation simulation"
    },
    {
      "source": "persistent-multiplayer",
      "sourceName": "Persistent multiplayer",
      "type": "uses",
      "target": "runtime-architecture",
      "targetName": "Runtime architecture"
    },
    {
      "source": "optional-web3-layer",
      "sourceName": "Optional Web3 layer",
      "type": "part-of",
      "target": "state-of-consequence",
      "targetName": "State of Consequence"
    },
    {
      "source": "optional-web3-layer",
      "sourceName": "Optional Web3 layer",
      "type": "depends-on",
      "target": "living-nation-simulation",
      "targetName": "Living nation simulation"
    },
    {
      "source": "natural-world-foundation",
      "sourceName": "Natural-world foundation",
      "type": "part-of",
      "target": "state-of-consequence",
      "targetName": "State of Consequence"
    },
    {
      "source": "world-generation",
      "sourceName": "World generation",
      "type": "part-of",
      "target": "natural-world-foundation",
      "targetName": "Natural-world foundation"
    },
    {
      "source": "planetary-foundation",
      "sourceName": "Earth-like planetary foundation",
      "type": "part-of",
      "target": "world-generation",
      "targetName": "World generation"
    },
    {
      "source": "geological-history-and-material",
      "sourceName": "Geological history and material",
      "type": "part-of",
      "target": "world-generation",
      "targetName": "World generation"
    },
    {
      "source": "geological-history-and-material",
      "sourceName": "Geological history and material",
      "type": "depends-on",
      "target": "planetary-foundation",
      "targetName": "Earth-like planetary foundation"
    },
    {
      "source": "canonical-geological-world",
      "sourceName": "Canonical geological world",
      "type": "part-of",
      "target": "world-generation",
      "targetName": "World generation"
    },
    {
      "source": "canonical-geological-world",
      "sourceName": "Canonical geological world",
      "type": "depends-on",
      "target": "geological-history-and-material",
      "targetName": "Geological history and material"
    },
    {
      "source": "tectonic-evolution",
      "sourceName": "Tectonic evolution",
      "type": "part-of",
      "target": "world-generation",
      "targetName": "World generation"
    },
    {
      "source": "tectonic-evolution",
      "sourceName": "Tectonic evolution",
      "type": "depends-on",
      "target": "planetary-foundation",
      "targetName": "Earth-like planetary foundation"
    },
    {
      "source": "tectonic-evolution",
      "sourceName": "Tectonic evolution",
      "type": "feeds",
      "target": "geological-history-and-material",
      "targetName": "Geological history and material"
    },
    {
      "source": "broad-solid-earth-geometry",
      "sourceName": "Broad solid-Earth geometry",
      "type": "part-of",
      "target": "world-generation",
      "targetName": "World generation"
    },
    {
      "source": "broad-solid-earth-geometry",
      "sourceName": "Broad solid-Earth geometry",
      "type": "depends-on",
      "target": "tectonic-evolution",
      "targetName": "Tectonic evolution"
    },
    {
      "source": "broad-solid-earth-geometry",
      "sourceName": "Broad solid-Earth geometry",
      "type": "depends-on",
      "target": "canonical-geological-world",
      "targetName": "Canonical geological world"
    },
    {
      "source": "surface-natural-systems",
      "sourceName": "Surface natural systems",
      "type": "part-of",
      "target": "world-generation",
      "targetName": "World generation"
    },
    {
      "source": "surface-natural-systems",
      "sourceName": "Surface natural systems",
      "type": "depends-on",
      "target": "broad-solid-earth-geometry",
      "targetName": "Broad solid-Earth geometry"
    },
    {
      "source": "map-and-spatial-model-prototype",
      "sourceName": "Map and spatial model prototype",
      "type": "part-of",
      "target": "natural-world-foundation",
      "targetName": "Natural-world foundation"
    },
    {
      "source": "map-and-spatial-model-prototype",
      "sourceName": "Map and spatial model prototype",
      "type": "constrained-by",
      "target": "canonical-geological-world",
      "targetName": "Canonical geological world"
    },
    {
      "source": "map-and-spatial-model-prototype",
      "sourceName": "Map and spatial model prototype",
      "type": "uses",
      "target": "runtime-architecture",
      "targetName": "Runtime architecture"
    },
    {
      "source": "runtime-architecture",
      "sourceName": "Runtime architecture",
      "type": "part-of",
      "target": "state-of-consequence",
      "targetName": "State of Consequence"
    },
    {
      "source": "project-journal",
      "sourceName": "Project Journal and System Map",
      "type": "uses",
      "target": "documentation-governance",
      "targetName": "Documentation governance"
    },
    {
      "source": "knowledge-delivery",
      "sourceName": "Knowledge delivery",
      "type": "supports",
      "target": "documentation-governance",
      "targetName": "Documentation governance"
    },
    {
      "source": "project-operations",
      "sourceName": "Project operations",
      "type": "uses",
      "target": "documentation-governance",
      "targetName": "Documentation governance"
    },
    {
      "source": "decision-governance",
      "sourceName": "Decision governance",
      "type": "supports",
      "target": "knowledge-delivery",
      "targetName": "Knowledge delivery"
    },
    {
      "source": "git-publication",
      "sourceName": "Git publication",
      "type": "depends-on",
      "target": "knowledge-delivery",
      "targetName": "Knowledge delivery"
    },
    {
      "source": "git-publication",
      "sourceName": "Git publication",
      "type": "uses",
      "target": "documentation-governance",
      "targetName": "Documentation governance"
    }
  ],
  "acceptedConcepts": [
    {
      "id": "WG-001",
      "truth": "Compatible worlds share one versioned Earth-like physical ruleset and geological reference framework; canonical positions use the accepted planet-fixed frame, and derived geodetic queries use one stable Earth-like oblate reference ellipsoid per world.",
      "owner": "Earth-Like Physical Framework",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-002",
      "truth": "World generation creates a geological prehistory; the playable physical world is the accumulated result of that history.",
      "owner": "Geological Prehistory",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-003",
      "truth": "Geological material preserves compact bulk composition and separate trace inventory; minerals and named rocks are derived where practical.",
      "owner": "Geological Material Composition",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-004",
      "truth": "Geological material is described through composition and history, coexisting solid/melt/fluid fractions, and structural state—not mutually exclusive rock, magma, sediment, and fluid types.",
      "owner": "Geological Material State",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-005",
      "truth": "Geological truth is sparse, three-dimensional, history-bearing, and independent of the map representation.",
      "owner": "Sparse 3D Geological World",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-006",
      "truth": "Geological events modify inherited 3D state through composable geometry operators while preserving chronology and cross-cutting relationships.",
      "owner": "Geological Geometry Operators",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-007",
      "truth": "Ordinary queries use canonical present state; compact provenance and constrained unresolved detail support explanation and deterministic refinement.",
      "owner": "Canonical Geological State and Refinement",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-008",
      "truth": "Geological identity, computational spatial domains, and system-specific sampling cells are separate concepts; partition boundaries must not create geological boundaries.",
      "owner": "Adaptive Spatial Partitioning",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-009",
      "truth": "Canonical geometry uses planet-fixed physical position; latitude, longitude, height, elevation, and depth are derived queries, lithostatic pressure follows actual overburden, and pore-fluid pressure remains separate.",
      "owner": "Depth, Pressure, and Thermal State",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-010",
      "truth": "Temperature is canonical history-bearing spatial state when present geometry and compact provenance cannot recover the promised future query truth; geothermal gradient is derived.",
      "owner": "Depth, Pressure, and Thermal State",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-011",
      "truth": "Tectonic plates are the earliest useful evolving lithospheric abstraction; their properties and relative motion supply causes for later geology.",
      "owner": "Tectonic Plates",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-012",
      "truth": "Boundary-relative motion produces tectonic interactions, persistent structures, and geological provinces—not final terrain.",
      "owner": "Tectonic Structures and Geological Provinces",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-013",
      "truth": "Broad solid-Earth geometry responds to whole-lithosphere buoyancy, loads, regional strength, tectonic forcing, disequilibrium, and relaxation.",
      "owner": "Broad Elevation and Isostatic Response",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-014",
      "truth": "Ground, seafloor, and elevation are semantic queries over the transformed 3D ground-material domain; heightmaps and meshes are derived products.",
      "owner": "Broad Elevation and Isostatic Response",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-015",
      "truth": "Seeds, selected Level 0 planetary contracts, and compatible generator/ruleset versions identify reproducible generation, while persisted canonical truth survives later algorithm changes.",
      "owner": "Architecture Overview",
      "implementation": "Unresolved"
    },
    {
      "id": "WG-016",
      "truth": "The authority owns canonical generation and refinement; clients receive only relevant subsets or derived views.",
      "owner": "Architecture Overview",
      "implementation": "Not started"
    },
    {
      "id": "WG-025",
      "truth": "Each world begins with a selected Level 0 planetary contract whose bounded causal parameters remain inside the supported Earth-like envelope and are inherited by later histories.",
      "owner": "Earth-Like Planetary Contract",
      "implementation": "Unresolved"
    }
  ],
  "explorationTopics": [
    {
      "id": "WG-017",
      "state": "recognized",
      "question": "How do weathering, erosion, transport, deposition, glaciation, and other surface processes transform inherited solid-Earth geometry into present terrain?",
      "owner": "Not created"
    },
    {
      "id": "WG-018",
      "state": "recognized",
      "question": "How should surface water, groundwater, drainage, rivers, lakes, wetlands, and coastlines arise from terrain, material, and climate causes?",
      "owner": "Not created"
    },
    {
      "id": "WG-019",
      "state": "recognized",
      "question": "What climate abstraction produces useful temperature, precipitation, wind, and seasonality from physical geography without becoming a full atmospheric simulator?",
      "owner": "Not created"
    },
    {
      "id": "WG-020",
      "state": "recognized",
      "question": "How should regolith, parent material, and soils develop from geology, climate, organisms, topography, and time?",
      "owner": "Not created"
    },
    {
      "id": "WG-021",
      "state": "recognized",
      "question": "How should vegetation and ecosystems emerge from climate, water, soil, disturbance, and biological history?",
      "owner": "Not created"
    },
    {
      "id": "WG-022",
      "state": "recognized",
      "question": "How should minerals, extractable resources, and natural energy potential derive from geological history and present physical conditions?",
      "owner": "Not created"
    },
    {
      "id": "WG-023",
      "state": "recognized",
      "question": "How should floods, erosion, landslides, and other natural hazards derive from the same physical state used by ordinary world queries?",
      "owner": "Not created"
    },
    {
      "id": "WG-024",
      "state": "recognized",
      "question": "Which physical properties must support later engineering, drainage, bearing-capacity, harbor, and infrastructure-suitability queries?",
      "owner": "Not created"
    }
  ],
  "decisions": [
    {
      "id": "ARCH-OPEN-001",
      "name": "Spatial foundations"
    },
    {
      "id": "ARCH-OPEN-002",
      "name": "Sparse 3D geological representation"
    },
    {
      "id": "ARCH-OPEN-003",
      "name": "Adaptive spatial partitioning"
    },
    {
      "id": "ARCH-OPEN-004",
      "name": "Canonical geological state and refinement"
    },
    {
      "id": "ARCH-OPEN-005",
      "name": "Geological geometry operators"
    },
    {
      "id": "ARCH-OPEN-006",
      "name": "Surface systems"
    },
    {
      "id": "ARCH-OPEN-007",
      "name": "Position, pressure, and thermal state"
    },
    {
      "id": "ARCH-OPEN-008",
      "name": "Broad elevation and isostatic response"
    },
    {
      "id": "ARCH-OPEN-009",
      "name": "Earth-like physical framework"
    },
    {
      "id": "ARCH-OPEN-010",
      "name": "Tectonic plate layer"
    },
    {
      "id": "ARCH-OPEN-011",
      "name": "Tectonic structures and geological provinces"
    },
    {
      "id": "ARCH-OPEN-012",
      "name": "Geological prehistory"
    },
    {
      "id": "ARCH-OPEN-013",
      "name": "Geological material composition"
    },
    {
      "id": "ARCH-OPEN-014",
      "name": "Geological material state"
    },
    {
      "id": "ARCH-OPEN-019",
      "name": "Earth-like planetary contract"
    },
    {
      "id": "ARCH-OPEN-015",
      "name": "Territory allocation"
    },
    {
      "id": "ARCH-OPEN-016",
      "name": "Persistence and compatibility"
    },
    {
      "id": "ARCH-OPEN-017",
      "name": "Networking"
    },
    {
      "id": "ARCH-OPEN-018",
      "name": "Player interface"
    }
  ],
  "historicalPosts": [
    {
      "title": "World Generation Has a Foundation, Not Yet a Generator",
      "snapshotDate": "2026-08-29",
      "slug": "2026-08-29-world-generation-foundation",
      "paragraphs": [
        "The project had established why the natural world must exist before political, economic, and social systems can build upon it. It had also accepted a causal direction: bounded Earth-like planetary causes lead into geological history, which accumulates into a sparse three-dimensional present world before later surface systems shape the landscape inherited by civilization.",
        "That foundation was conceptual, not implemented. Seventeen world-generation concepts had accepted but partial coverage. They separated physical truth from map presentation, geological identity from computational partitions, and canonical present state from disposable meshes or sampled views. Eight later topics—including surface processes, water, climate, soils, ecosystems, resources, hazards, and engineering properties—were recognized as important questions without accepted models.",
        "The repository also held nineteen groups of unresolved architecture and world-generation choices. No option in those groups had become accepted merely because it was listed. There was no Rust workspace or game/runtime source code, and the first implementation milestone—the map and spatial model prototype—had not started.",
        "The practical consequence was clear: the project had a governed knowledge foundation strong enough to guide implementation, but not a completed world generator. The immediate path was to build the bounded map prototype while preserving provisional spatial measurements as prototype choices rather than promoting them into permanent world ontology.",
        "This post remains useful as a dated explanation of that moment. It must not be used to determine the present system state, current counts, or current implementation progress."
      ]
    }
  ]
} as const;
